name: python linter

on:
  push:
    paths: 
      - "*.py"

jobs:
  code-linting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: setup linter ruff
        run: pip install ruff

      - name: check the code
        run: ruff check .
        
